### ISSUE TITLE
youtube_dl error

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Media-Player#2]
Have you seen this?
```
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Here's the bigger dump:

```
C:\Python\Anaconda3\python.exe C:/Python/PycharmProjects/GooeyGUI/DemoPrograms/MediaPlayer/Media-Player-master/streaming_media_player.py
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Python\Anaconda3\lib\site-packages\youtube_dl\extractor\youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "C:\Python\Anaconda3\lib\site-packages\youtube_dl\extractor\youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Python\Anaconda3\lib\site-packages\youtube_dl\extractor\youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "C:\Python\Anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Python\Anaconda3\lib\site-packages\youtube_dl\extractor\youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "C:\Python\Anaconda3\lib\site-packages\youtube_dl\extractor\youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Python\Anaconda3\lib\site-packages\youtube_dl\extractor\youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "C:\Python\Anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by PySimpleGUI** [comment]
Nevermind.... I did another pip install of youtube_dl and it fixed it!

**Comment by israel-dryer** [comment]
ok. cool. I had put that in my comments for myself, but didn't explain what it was.
